"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:56:55.354268+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_date, current_timestamp, input_file_name, when, broadcast, lit
from pyspark.sql.types import StringType, DoubleType, TimestampType
import sys

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read transactions data from CSV
    transactions_df = spark.read.option("header", "true").csv(input_path, inferSchema=True)
    
    # Add metadata columns
    transactions_enriched_df = transactions_df.withColumn("ingestion_timestamp", current_timestamp()) \
                                              .withColumn("source_file_name", input_file_name()) \
                                             .withColumn("ingestion_date", current_date()) \
                                             .withColumn("pipeline_run_id", lit(run_id))
    
    # Write to Bronze layer partitioned by ingestion_date
    transactions_enriched_df.write.partitionBy("ingestion_date").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze layer data with partition pruning
    bronze_df = spark.read.parquet(bronze_path).where(col("ingestion_date") == run_date)
    
    # Cast columns to correct types
    silver_df = bronze_df.withColumn("amount", col("amount").cast(DoubleType())) \
                          .withColumn("transaction_timestamp", col("transaction_timestamp").cast(TimestampType())) \
                         .withColumn("transaction_id", col("transaction_id").cast(StringType())) \
                         .withColumn("customer_id", col("customer_id").cast(StringType())) \
                         .withColumn("payment_method", col("payment_method").cast(StringType()))
    
    # Filter out NULL transaction_id and negative amounts
    silver_df = silver_df.filter(col("transaction_id").isNotNull() & (col("amount") >= 0))
    
    # Deduplicate on transaction_id, keeping the latest record
    silver_df = silver_df.sortWithinPartitions("transaction_id", "transaction_timestamp", ascending=False) \
                          .dropDuplicates(["transaction_id"])
    
    # Read merchants data and cache it
    merchants_df = spark.read.parquet(merchants_path).cache()
    
    # Join with merchants and add quality_flag column
    silver_df = silver_df.join(broadcast(merchants_df), silver_df["merchant_id"] == merchants_df["merchant_id"], "left_outer") \
                        .withColumn("quality_flag", when(col("merchant_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    
    # Write to Silver layer partitioned by ingestion_date
    silver_df.write.partitionBy("ingestion_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = SparkSession.builder.appName("ComplianceAuditPipeline").getOrCreate()
    
    # Define paths and run details
    input_path = "s3://path/to/bronze/transactions"
    bronze_output_path = "s3://path/to/silver/transactions"
    merchants_path = "s3://path/to/merchants"
    silver_output_path = "s3://path/to/silver/transactions"
    run_date = "2023-10-01"
    run_id = "run_12345"
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_output_path, run_date, run_id)
    
    # Transform to Silver layer
    transform_silver(spark, bronze_output_path, merchants_path, silver_output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, when, max, collect_set, coalesce, current_date, current_timestamp, input_file_name
from pyspark.sql.types import DoubleType, StringType, TimestampType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Load the Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("status") == "COMPLETED")
    
    # Calculate required metrics
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write the merchant performance data to the output path
    merchant_performance_df.write.partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Load the Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("status") == "COMPLETED")
    
    # Calculate required metrics
    customer_ltv_df = silver_df.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("transaction_timestamp").alias("first_txn_date"),
            max("transaction_timestamp").alias("last_txn_date"),
            collect_set("payment_method").alias("payment_methods")
        )
    
    # Calculate preferred payment method
    customer_ltv_df = customer_ltv_df.withColumn("preferred_payment_method", 
                                                 coalesce(expr("transform(payment_methods, x -> x)[argsort(transform(payment_methods, x -> count(payment_methods) over (partition by x)))[size(payment_methods) - 1]]"), lit(None)))

    # Write the customer LTV data to the output path
    customer_ltv_df.write.parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Load the Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Calculate required metrics
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id").isNotNull()).alias("unique_customers"),
            count(col("merchant_id").isNotNull()).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write the daily summary data to the output path
    daily_summary_df.write.partitionBy("date").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths for each gold component
    merchant_performance_output_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_output_path = f"{gold_output_dir}/daily_summary"

    # Build the merchant performance data
    build_merchant_performance(spark, silver_path, merchant_performance_output_path, run_date)
    
    # Build the customer LTV data
    build_customer_ltv(spark, silver_path, customer_ltv_output_path)
    
    # Build the daily summary data
    build_daily_summary(spark, silver_path, daily_summary_output_path, run_date)
    
    # Write run metadata to JSON
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "components": ["merchant_performance", "customer_ltv", "daily_summary"]
    }
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

if __name__ == "__main__":
    spark = SparkSession.builder.appName("GoldLayerPipeline").getOrCreate()
    silver_path = "s3://your-silver-layer-path"
    gold_output_dir = "s3://your-gold-layer-output-path"
    run_date = "2023-10-01"
    
    run_gold(spark, silver_path, gold_output_dir, run_date)
